name: Deploy to VPS

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔎 Checkout code
        uses: actions/checkout@v2

      - name: 🏗️ Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy to VPS
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          DEPLOY_DIR=""
          SERVICE_NAME=""

          if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
            DEPLOY_DIR="/Projects/Flexi/Production"
            SERVICE_NAME="flexi"
          else
            DEPLOY_DIR="/Projects/Flexi/Dev"
            SERVICE_NAME="flexi_dev"
          fi

          ssh -o StrictHostKeyChecking=no root@85.215.185.110 << EOF
            cd $DEPLOY_DIR
            git restore .
            git pull origin $BRANCH_NAME
            dotnet build
            systemctl restart $SERVICE_NAME
          EOF
